#!/bin/bash
# Hook Type: PreToolUse (Bash) — Forbidden Commands Interceptor
# Generated by AgentHub HookManager
# Hash: c1ca26aa3258a155606da11dcbc1de6b

INPUT=$(cat)

# Extract command — use jq if available, otherwise grep fallback (Windows Git Bash)
if command -v jq &>/dev/null; then
  TOOL=$(echo "$INPUT" | jq -r '.tool_name // ""')
  [ "$TOOL" != "Bash" ] && exit 0
  CMD=$(echo "$INPUT" | jq -r '.tool_input.command // ""')
else
  echo "$INPUT" | grep -q '"tool_name".*"Bash"' || exit 0
  CMD=$(echo "$INPUT" | sed -n 's/.*"command"\s*:\s*"\([^"]*\)".*/\1/p')
fi

# Block kill-port / taskkill / Stop-Process targeting node
if echo "$CMD" | grep -qiE 'kill-port|taskkill.*node|Stop-Process.*node'; then
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"禁止: kill-port/taskkill/Stop-Process — 本機多專案運行，禁止批量殺 process"}}'
  exit 0
fi

# Block --no-verify
if echo "$CMD" | grep -qE '\-\-no-verify'; then
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"禁止: --no-verify — 請修復 hook 問題而非跳過"}}'
  exit 0
fi

# Block force push to main/master
if echo "$CMD" | grep -qE 'git\s+push\s+.*--force\s.*(main|master)'; then
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"禁止: force push 到 main/master"}}'
  exit 0
fi

exit 0
