#!/bin/bash
# G4 Knowledge Check — 自動產生，勿手動修改
# Hook Type: PostToolUse (Edit) — Knowledge Doc Sync Reminder
# Generated by AgentHub HookManager
# Hash: g4v2

INPUT=$(cat)

# Extract file_path — use jq if available, otherwise grep fallback (Windows Git Bash)
if command -v jq &>/dev/null; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_response.filePath // .tool_input.file_path // ""')
else
  FILE_PATH=$(echo "$INPUT" | sed -n 's/.*"filePath"\s*:\s*"\([^"]*\)".*/\1/p' | head -1)
  if [ -z "$FILE_PATH" ]; then
    FILE_PATH=$(echo "$INPUT" | sed -n 's/.*"file_path"\s*:\s*"\([^"]*\)".*/\1/p' | head -1)
  fi
fi

# If editing a .knowledge/ file, no reminder needed
if echo "$FILE_PATH" | grep -qE '(^|/)\.knowledge/'; then
  exit 0
fi

# Only trigger for architecture-critical directories:
#   electron/services/  — 核心服務邏輯
#   electron/ipc/       — IPC 通道定義
#   electron/migrations/ — 資料庫 schema 變更
#   electron/types/     — 共用型別定義
if ! echo "$FILE_PATH" | grep -qE 'electron/(services|ipc|migrations|types)/'; then
  exit 0
fi

FILENAME=$(basename "$FILE_PATH")

echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PostToolUse\",\"additionalContext\":\"📝 G4 文件同步提醒：你剛修改了 ${FILENAME}（架構關鍵路徑）。根據文件治理規則，此路徑的變更必須同步更新相關 .knowledge/ 文件（architecture.md、coding-standards.md 等）。請確認是否有需要更新的規範文件。\"}}"
exit 0
