#!/bin/bash
# Git Commit Message Check — 自動產生，勿手動修改
# Hook Type: PreToolUse (Bash) — Conventional Commits Enforcer
# Generated by AgentHub HookManager
# Hash: {{GENERATED_HASH}}

log_hook() {
  local RESULT="$1" REASON="$2"
  mkdir -p .claude 2>/dev/null
  echo "{\"hook\":\"git-commit-check\",\"type\":\"PreToolUse\",\"result\":\"${RESULT}\",\"reason\":\"${REASON}\",\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)\"}" >> .claude/hook-execution.jsonl
}

INPUT=$(cat)

# Extract command — use jq if available, otherwise grep fallback (Windows Git Bash)
if command -v jq &>/dev/null; then
  TOOL=$(echo "$INPUT" | jq -r '.tool_name // ""')
  [ "$TOOL" != "Bash" ] && exit 0
  CMD=$(echo "$INPUT" | jq -r '.tool_input.command // ""')
else
  echo "$INPUT" | grep -q '"tool_name".*"Bash"' || exit 0
  CMD=$(echo "$INPUT" | sed -n 's/.*"command"\s*:\s*"\([^"]*\)".*/\1/p')
fi

# Only intercept git commit commands
if ! echo "$CMD" | grep -qE 'git\s+commit'; then
  log_hook "passed" "non-commit command"
  exit 0
fi

# Extract commit message from -m flag (single or double quotes)
MSG=$(echo "$CMD" | sed -n "s/.*-m[[:space:]]*'\([^']*\)'.*/\1/p")
if [ -z "$MSG" ]; then
  MSG=$(echo "$CMD" | sed -n 's/.*-m[[:space:]]*"\([^"]*\)".*/\1/p')
fi

# Skip validation for complex forms (heredoc, variable substitution, etc.)
if [ -z "$MSG" ]; then
  log_hook "passed" "complex commit format - skipping"
  exit 0
fi

# Validate Conventional Commits format
# Pattern: type(optional-scope): description (min 5 chars)
PATTERN='^(feat|fix|refactor|test|docs|chore|style|perf|build|ci)(\([^)]+\))?: .{5,}'
if ! echo "$MSG" | grep -qE "$PATTERN"; then
  log_hook "blocked" "invalid commit message format"
  echo "{\"hookSpecificOutput\":{\"hookEventName\":\"PreToolUse\",\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"❌ Commit 訊息格式不符合 Conventional Commits 規範\\n\\n正確格式：type(scope): description\\n合法 type：feat | fix | refactor | test | docs | chore | style | perf | build | ci\\n\\n範例：\\n  feat: add user authentication\\n  fix(auth): resolve token expiry bug\\n  docs: update API documentation\\n\\n你的訊息：${MSG}\"}}"
  exit 0
fi

log_hook "passed" "valid commit message"
exit 0
